### ISSUE TITLE
Version mismatch issue

### ISSUE THREAD

**Issue by gjossep** [wx9698/carlaviz#1]
Hi, 
Im trying to run this with my compiled carla. But I cant get your backend to work, this is the following error I get while running:

`WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.9 
WARNING: Simulator API version  = 0.9.9-12-gb67ba6c3-dirty 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
./run.sh: line 16:     6 Aborted                 (core dumped) ./carlaviz/backend/bin/backend ${CARLA_SERVER_IP} ${CARLA_SERVER_PORT}
`

As you can see the version is right, my compiled one just has extra things on it (Not sure why) But im sure its 0.9.9

**Comment by wx9698** [comment]
CarlaViz 0.9.9 works with CARLA 0.9.9.2, which is the latest version with some bugs fixed.

**Comment by gjossep** [comment]
Hi,
Im complied carla with the latest version from source. 
Im still getting your error, anything I can do to fix it?
Thanks

**Comment by wx9698** [comment]
Hi,

I think the latest source files of CARLA contain some changes from 0.9.9.2. Thus, I recommend you to download from this [page](https://github.com/carla-simulator/carla/releases). Please download 0.9.9.2 version if possible.
