### ISSUE TITLE
How can I customize my lader, lidar, camera data?

### ISSUE THREAD

**Issue by BupyeongHealer** [wx9698/carlaviz#11]
Helo!
Thanks to your repo. I can visualize example data(example.py) in web application.
ubuntu : 18.04
carla-simualtor : 0.9.9
installation : using docker image

So, I want to customize my lader, lidar, camera data. 
But, I installed carlaviz using docker image, where can I find backend folder & sensor-related-folder?

Thanks.

**Comment by wx9698** [comment]
If you spawn sensors in Carla, you will see the visualizations of them in the browser. There is no need for you to configure other things.

**Comment by BupyeongHealer** [comment]
Actually I mean
I try to substitute real self-driving car data(ex.ros topic)for carla sensor data. So When I build the carlaviz tool manually, what source code is related to sensor data?

**Comment by wx9698** [comment]
It's in backend/src/backend/proxy/carla_proxy.cpp. 

If you are looking for a converter that can convert from any data to the data format that this frontend can visualize, I suggest you take a look at this repo: https://github.com/wx9698/xviz.

**Comment by BupyeongHealer** [comment]
@wx9698 Wow awesome! Thanks a lot.
