### ISSUE TITLE
Frontend does not connect to backend when Carla is running on another machine

### ISSUE THREAD

**Issue by lrstttl** [wx9698/carlaviz#12]
Hello,

my setup is the following: I have 2 computers, one running Windows and a CARLA build from source. The other one is running Ubuntu 16.04, where I built carlaviz v0.9.9 from source. I am trying to run backend and frontend of carlaviz v0.9.9 on the Ubuntu 16.04 machine. Therefore I start the backend on the Linux machine using 
```
/path/to/carlaviz/backend/bin/backend WINDOWS-HOSTNAME 2000
```
and the backend successfully connects to CARLA running on Windows. On the Windows machine, I can start the frontend using the `mjxu96/carlaviz:0.9.9` docker image with `CARLAVIZ_HOST_IP=LINUX-HOSTNAME` and it works perfectly. 
However, when I want to start the frontend on the Linux machine using
```
cd /path/to/carlaviz/frontend/ && yarn start 
```
the frontend cannot connect to the backend and the output is the same as in #5.

Am I missing something?

**Comment by wx9698** [comment]
Could you try to run
```bash
CARLAVIZ_HOST_IP=LINUX-HOSTNAME yarn start
```

and see if that works?

**Comment by lrstttl** [comment]
Using `CARLAVIZ_HOST_IP=LINUX-HOSTNAME yarn start` works, thank you very much! Somehow the default `localhost` does not work.

And yes, I am from the Windows machine to `http://LINUX-HOSTNAME:8080/` which works as expected now.

**Comment by wx9698** [comment]
Yes, that is because the frontend sends the code to the browser and your browser actually runs the code. So if you use the browser on Windows machine and the ip address is "localhost", it cannot connect to the backend. Anyway, glad to see it works.
