### ISSUE TITLE
Carlaviz is not working in 0.9.10.1 version

### ISSUE THREAD

**Issue by pjw1** [wx9698/carlaviz#16]
Hey,

I've just updated Carla simulator and Carlaviz version 0.9.9 to 0.9.10.1.
Since I upgraded, Carlaviz is not working.

I guess it is due to the version mismatch problem, simulator api version is 784d9b9f, not 0.9.10.1.
It is right that version mismatch cause this problem? 
Anyone can run Carlaviz on 0.9.10.1?
(I ran Carla simulator before Carlaviz)

![carlaviz error](https://user-images.githubusercontent.com/19548825/100413176-10de8180-30ba-11eb-8982-549422ba29e2.PNG)
![캡처](https://user-images.githubusercontent.com/19548825/100413211-2b185f80-30ba-11eb-8008-4ab9bc0ad7d9.PNG)

**Comment by wx9698** [comment]
@pjw1 It seems that you do not enter correct ip address when starting the container. Please change CARLAVIZ_HOST_IP from localhost to 59.10.147.138 and try again.

**Comment by pjw1** [comment]
Haha yes I miss that.

Thanks a lot!
