### ISSUE TITLE
CMake Error: include could not find load file

### ISSUE THREAD

**Issue by johschmitz** [wx9698/carlaviz#3]
I am trying to build the backend
```
cd backend
mkdir build
cd build
cmake ../
```
but I get the following error:
```
CMake Error at CMakeLists.txt:9 (include):
  include could not find load file:

    third_party/LibCarla/cmake/CMakeLists.txt.in
```

**Comment by wx9698** [comment]
Please first run the setup.sh script under the backend/setup folder. Some files and libraries need to be downloaded and initialized first.
