### ISSUE TITLE
Can't display carla information just frontend in http://127.0.0.1:8080/

### ISSUE THREAD

**Issue by huan0808** [wx9698/carlaviz#5]
Hello, my host is ubuntu 18.04 and carla version is 0.9.9
And I follow the instuction of the readme run with rocker ,but  unfortunately it doesn't work for me.
![image](https://user-images.githubusercontent.com/49682558/89096236-bc770e00-d407-11ea-8d19-759521965467.png)

It seems that backend meet something wrong when it launch.

>Make sure you have launched the carla server.
Launching backend.
2020-08-01 06:49:07 [INFO]     Connecting to Carla Server on localhost:2000...
2020-08-01 06:49:07 [INFO]     Connected to Carla Server, Server version is: 0.9.9
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
./run.sh: line 16:     6 Aborted                 (core dumped) ./carlaviz/backend/bin/backend ${CARLA_SERVER_IP} ${CARLA_SERVER_PORT}
Backend launched.
Launching frontend
yarn run v1.22.4
warning package.json: No license field
$ webpack-dev-server --host 0.0.0.0 --disable-host-check --env.live --progress --hot --open
10% building 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/carla/carlaviz/frontend
93% after chunk asset optimization SourceMapDevToolPluginFrontend launched. Please open your browser
ℹ ｢wdm｣: Hash: 0e269bd408f4fb0a1571
Version: webpack 4.42.0
Time: 11520ms
Built at: 08/01/2020 6:49:26 AM
                               Asset      Size  Chunks                   Chunk Names
573fe91c6c748074195655e1f0159864.png  7.61 KiB          [emitted]        
                           bundle.js  9.36 MiB     app  [emitted]        app
                       bundle.js.map  11.5 MiB     app  [emitted] [dev]  app
Entrypoint app = bundle.js bundle.js.map
[0] multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./src/app.js 52 bytes {app} [built]
[./node_modules/@deck.gl/core/dist/esm/index.js] 2.78 KiB {app} [built]
[./node_modules/@deck.gl/layers/dist/esm/index.js] 1.01 KiB {app} [built]
[./node_modules/@streetscape.gl/monochrome/dist/esm/index.js] 560 bytes {app} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {app} [built]
[./node_modules/react/index.js] 190 bytes {app} [built]
[./node_modules/streetscape.gl/dist/esm/index.js] 78 bytes {app} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {app} [built]
[./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080] (webpack)-dev-server/client?http://0.0.0.0:8080 4.29 KiB {app} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {app} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {app} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {app} [built]
[./src/app.js] 10.6 KiB {app} [built]
    + 1454 hidden modules
ℹ ｢wdm｣: Compiled successfully.

**Comment by wx9698** [comment]
Hi,

It seems that you backend did not launch.

```bash
Make sure you have launched the carla server.
Launching backend.
2020-08-01 06:49:07 [INFO] Connecting to Carla Server on localhost:2000...
2020-08-01 06:49:07 [INFO] Connected to Carla Server, Server version is: 0.9.9
terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc
./run.sh: line 16: 6 Aborted (core dumped) ./carlaviz/backend/bin/backend ${CARLA_SERVER_IP} ${CARLA_SERVER_PORT}
```

Currently the docker version of carlaviz:0.9.9 only works with Carla 0.9.9.2. It cannot work with 0.9.9.1, 0.9.9.3 or 0.9.9.4. Please change your Carla server's version and let me know if this error still exists.

**Comment by huan0808** [comment]
After remove carla and download 0.9.9.2 version  it works.Thank you for your help !
