### ISSUE TITLE
Can't display carla information just frontend, using Carla 0.9.9.2

### ISSUE THREAD

**Issue by lynnpepin** [wx9698/carlaviz#6]
Similar to issue 5 at https://github.com/wx9698/carlaviz/issues/5, except we are using Carla 0.9.9.2. Just like in Issue 5, we navigate to localhost:8083 but still have the "Launch the backend and refresh" issue.

Output is below, noting that we don't have the same error that closes the backend:

```
Make sure you have launched the carla server.
Launching backend.
2020-08-04 14:56:01 [INFO]     Connecting to Carla Server on localhost:2000...
2020-08-04 14:56:01 [INFO]     Connected to Carla Server, Server version is: 4dc4cb81
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API
WARNING: Client API version     = 0.9.9
WARNING: Simulator API version  = 4dc4cb81
2020-08-04 14:56:03 [INFO]     Waiting for a drawing client to connect. Listening to port 8089....
2020-08-04 14:56:03 [INFO]     Waiting for a frontend to connect. Listening to port 8081....
Backend launched.
Launching frontend
yarn run v1.22.4
warning package.json: No license field
$ webpack-dev-server --host 0.0.0.0 --disable-host-check --env.live --progress --hot --open
10% building 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://0.0.0.0:8083/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/carla/carlaviz/frontend
ℹ ｢wdm｣: Hash: 24084e845cfb1f730fbb
Version: webpack 4.42.0
Time: 6970ms
Built at: 08/04/2020 2:56:16 PM
                               Asset      Size  Chunks                   Chunk Names
573fe91c6c748074195655e1f0159864.png  7.61 KiB          [emitted]
                           bundle.js  9.36 MiB     app  [emitted]        app
                       bundle.js.map  11.5 MiB     app  [emitted] [dev]  app
Entrypoint app = bundle.js bundle.js.map
[0] multi (webpack)-dev-server/client?http://0.0.0.0:8083 (webpack)/hot/dev-server.js ./src/app.js 52 bytes {app} [built]
[./node_modules/@deck.gl/core/dist/esm/index.js] 2.78 KiB {app} [built]
[./node_modules/@deck.gl/layers/dist/esm/index.js] 1.01 KiB {app} [built]
[./node_modules/@streetscape.gl/monochrome/dist/esm/index.js] 560 bytes {app} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {app} [built]
[./node_modules/react/index.js] 190 bytes {app} [built]
[./node_modules/streetscape.gl/dist/esm/index.js] 78 bytes {app} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {app} [built]
[./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8083] (webpack)-dev-server/client?http://0.0.0.0:8083 4.29 KiB {app} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {app} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {app} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {app} [built]
[./src/app.js] 10.6 KiB {app} [built]
    + 1454 hidden modules
ℹ ｢wdm｣: Compiled successfully.
Frontend launched. Please open your browser
```

I can confirm the version using `apt-cache`, as follows:

```
$ apt-cache policy carla-simulator
carla-simulator:
  Installed: 0.9.9.2-1
  Candidate: 0.9.9.2-1
  Version table:
 *** 0.9.9.2-1 500
        500 http://dist.carla.org/carla-0.9.9 all/main amd64 Packages
        100 /var/lib/dpkg/status
```

Is it possible that this `0.9.9.2-1` is somehow different than `0.9.9.2`? Has anyone else had this issue and found a way to fix it? I should also note that the simulator version is listed as `4dc4cb81`, which I found strange. If anyone else is having this issue, we may be able to find a solution together here

**Comment by wx9698** [comment]
Hi, it seems that the backend does connect the frontend. Could you provide the command when launching the docker and what is your system os?

**Comment by lynnpepin** [comment]
Hi, we're on Ubuntu 18.04 using the command `docker run -it --network="host" -e CARLAVIZ_HOST_IP=localhost -e CARLA_SERVER_IP=localhost -e CARLA_SERVER_PORT=2000 mjxu96/carlaviz:0.9.9`

This also happens when we run it with `carlasim/carlaviz:latest`

**Comment by wx9698** [comment]
Are you using it in the local machine?

**Comment by lynnpepin** [comment]
We're running both Carla and the CarlaViz Docker on a remote server, and ssh tunneling the port to our local machines to use CarlaViz in the browser.

**Comment by wx9698** [comment]
Have you tunnelled the 8081 and 8089 ports. They are the ports used for the communications between frontend and backend.

Also, if your remote server has the external ip, you can replace the env CARLAVIZ_HOST_IP's value with your server's ip when launching the docker.

Please let me know if this work for you.

**Comment by lynnpepin** [comment]
Hi, I've tried again, forwarding ports 8080, 8081, and 8089, but we still have this issue.

Notably, we got it to work one time (when only forwarding ports 8080 and 8081), but we don't know why it worked

**Comment by wx9698** [comment]
That is wired. Have you tried setting the env value when starting the docker?

**Comment by lynnpepin** [comment]
We've found the issue -- it seems that we need to start Carla before CarlaViz-- starting Carla after CarlaViz leads to this issue! Thank you
