### ISSUE TITLE
modify browser style

### ISSUE THREAD

**Issue by hjhanjing** [wx9698/carlaviz#71]
Thank you very much for the open source code. Is there a docker carlaviz method? Or I want to modify the current browser visualization style, where I can get the carla emulator data from the image, and the format of the carla data, and where I should go to modify the css and js.

**Comment by mjxu96** [comment]
> Is there a docker carlaviz method?

There is a docker version. Example: https://github.com/mjxu96/carlaviz/tree/master/examples

> where I can get the carla emulator data from the image

CarlaViz backend reads Carla's image data [here ](https://github.com/mjxu96/carlaviz/blob/master/backend/include/carlaviz/simulators/carla.h#L367). It then converts the image data into png format and encodes into xviz protocol [here](https://github.com/mjxu96/carlaviz/blob/master/backend/include/carlaviz/translations/xviz.h#L339) using [xviz](https://github.com/mjxu96/xviz) library. Finally, it sends out the data in the protobuf format to CarlaViz frontend and frontend will decode it and render it in the browser.

> and where I should go to modify the css and js.

https://github.com/mjxu96/carlaviz/tree/master/frontend

**Comment by hjhanjing** [comment]
Thank you very much for your reply, which is very helpful to me
