### ISSUE TITLE
Any plan to update the CarlaPainter?

### ISSUE THREAD

**Issue by soumya997** [wx9698/carlaviz#74]
just want to know if there is any plan to update the CarlaPainter (carla_painter.py), its a great visualization component and would love to have it. Also is there any Rviz2 plugin for the polygon in ROS2?

**Comment by mjxu96** [comment]
hmm myself does not have plan recently but happy to review/merge any codes/PR.

**Comment by mjxu96** [comment]
> Also is there any Rviz2 plugin for the polygon in ROS2?

Sorry not very familiar with ROS2.

**Comment by soumya997** [comment]
thank you for your response! Will try if i can add that.

**Comment by 1ywan** [comment]
> thank you for your response! Will try if i can add that.

hi, want to know if this issue is processing? It seems not only CarlaPainter class on Python side need to be updated, but also backend need to support paint interface again?

if it is possible using the carla.world.debug interfaces return, and render on the carlaviz directly?

**Comment by mjxu96** [comment]
> hi, want to know if this issue is processing?

I personally am not working on it. 

> It seems not only CarlaPainter class on Python side need to be updated, but also backend need to support paint interface again?

Correct, both need to be updated.

> if it is possible using the carla.world.debug interfaces return, and render on the carlaviz directly?

It sounds interesting. Happy to help review/merge related changes.
