### ISSUE TITLE
How to access the Carla Map information using python apis similar to what you use in web interface?

### ISSUE THREAD

**Issue by harmanpreet93** [wx9698/carlaviz#8]

**Comment by harmanpreet93** [comment]
Are there python APIs available to save the map information as shown in the figure below? 

Image captured from https://www.youtube.com/watch?v=vA1l7M6OEi0

<img width="820" alt="Screenshot 2020-09-14 at 5 16 25 PM" src="https://user-images.githubusercontent.com/9989122/93139022-082b0180-f6ae-11ea-8f26-783623dbd1ab.png">

**Comment by wx9698** [comment]
Related codes are https://github.com/wx9698/carlaviz/blob/master/backend/src/backend/utils/utils.cpp#L139 . You can convert it back to PythonAPI to extract the map data.
